sudo: false
language: node_js
node_js:
- 'stable'
after_success: npm run coveralls
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: HFzTuz67kFewMd1bZM1RxMWji+CGKf9qpGFj2k0DtDieCSuAG48gYr+ccxNvG8qalLAKrqb4Q0TX9MZbwREDqfbin5shFjtV9WBsL1issuSmo6vwqy63Fxz+7mzI16TpTLvxoxGOtwUi2OKLNAjmtdXsyxaQl6LOxRFtf3cFiWM=
